#!/usr/bin/env groovy

//  list of apps
def microserviceJobList = ["tom-microservice", "donal-microservice"]

//  Globals for across all the jobs
def gitBaseUrl = "https://my-git.com/project"
def pipelineNamespace = "ci-cd"
newLine = System.getProperty("line.separator")
def pipelineGeneratorVersion = "${JOB_NAME}.${BUILD_ID}"
def projectDevNamespace = "labs-dev"
def projectTestNamespace = "labs-test"
def jenkinsGitCreds = "jenkins-id-as-seen-in-j-man"

//  Common functions repeated across the jobs
def buildWrappers(context) {
    context.ansiColorBuildWrapper {
        colorMapName('xterm')
    }
}

def notifySlack(context) {
    context.slackNotifier {
        notifyAborted(true)
        notifyBackToNormal(true)
        notifyFailure(true)
        notifyNotBuilt(true)
        notifyRegression(true)
        notifyRepeatedFailure(true)
        notifySuccess(true)
        notifyUnstable(true)
    }
}

def rotateLogs(context) {
    context.logRotator {
        daysToKeep(100)
        artifactNumToKeep(2)
    }
}

def coverageReport(context) {
    context.cobertura('reports/coverage/cobertura.xml') {
        failNoReports(true)
        sourceEncoding('ASCII')
        // the following targets are added by default to check the method, line and conditional level coverage
        methodTarget(80, 40, 20)
        lineTarget(80, 40, 20)
        conditionalTarget(70, 40, 20)
    }
    context.publishHtml {
        report('reports/coverage/lcov-report') {
            reportName('HTML Code Coverage Report')
            allowMissing(false)
            alwaysLinkToLastBuild(false)
        }
    }
}

// build > deploy-test > deploy-prod for each microservice
microserviceJobList.each {
    def appName = it
    def buildJobName = it + "-build-dev"
    def deployTest = it + "-deploy-test"
    def deployProd = it + "-deploy-prod"
    def jobDescription = "THIS JOB WAS GENERATED BY THE JENKINS SEED JOB - ${pipelineGeneratorVersion}.  \n"  + it + "build job for the microservice apps"

    job(buildJobName) {
        description(jobDescription)
        label('npm-build-pod')

        rotateLogs(delegate)

        wrappers {
            buildWrappers(delegate)

            preScmSteps {
                // Fails the build when one of the steps fails.
                failOnError(true)
                // Adds build steps to be run before SCM checkout.
                steps {
                    shell('git config --global http.sslVerify false')
                }
            }
        }
        scm {
            git {
                remote {
                    name('origin')
                    url(gitBaseUrl + appName)
                    credentials(jenkinsGitCreds)
                }
                branch('master')
            }
        }
        // triggers {
        //   cron('H/60 H/2 * * *')
        // }
        steps {
            steps {
                shell('#!/bin/bash' + newLine +
                        'NAME=' + appName  + newLine +
                        'export NODE_ENV=ci' + newLine +
                        'set -o xtrace' + newLine +
                        'scl enable rh-nodejs6 \'npm install\'' + newLine +
                        'scl enable rh-nodejs6 \'./node_modules/.bin/gulp lint\'' + newLine +
                        'scl enable rh-nodejs6 \'./node_modules/.bin/gulp test\'' + newLine +
                        'mkdir package-contents' + newLine +
                        'mv server Dockerfile package.json server.js package-contents' + newLine +
                        'oc patch bc ${NAME} -p "spec:' + newLine +
                        '   nodeSelector:' + newLine +
                        '   output:' + newLine +
                        '     to:' + newLine +
                        '       kind: ImageStreamTag' + newLine +
                        '       name: \'${NAME}:${JOB_NAME}.${BUILD_NUMBER}\'"' + newLine +
                        'oc start-build ${NAME} --from-dir=package-contents/ --follow')
            }
        }
        publishers {
            archiveArtifacts('**')

            coverageReport(delegate)

            xUnitPublisher {
                tools {
                    jUnitType {
                        pattern('reports/**/unit-report.xml')
                        skipNoTestFiles(false)
                        failIfNotNew(true)
                        deleteOutputFiles(true)
                        stopProcessingIfError(true)
                    }
                }

                thresholds {
                    failedThreshold {
                        failureThreshold('0')
                        unstableThreshold('')
                        unstableNewThreshold('')
                        failureNewThreshold('')
                    }
                }

                thresholdMode(0)
                testTimeMargin('3000')
            }
            downstreamParameterized {
                trigger(deployTest) {
                    condition('SUCCESS')
                    parameters {
                        predefinedBuildParameters{
                            properties("BUILD_TAG=\${JOB_NAME}.\${BUILD_NUMBER}")
                            textParamValueOnNewLine(true)
                        }
                    }
                }
            }
            notifySlack(delegate)
        }
    }


    job(deployTest) {
        description(jobDescription)
        parameters{
            string{
                name("BUILD_TAG")
                defaultValue("my-app-build.1234")
                description("The BUILD_TAG is the \${JOB_NAME}.\${BUILD_NUMBER} of the successful build to be promoted.")
            }
        }
        rotateLogs(delegate)

        wrappers {
            buildWrappers(delegate)
        }
        steps {
            steps {
                shell('#!/bin/bash' + newLine +
                        'set -o xtrace' + newLine +
                        'PIPELINES_NAMESPACE=' + pipelineNamespace  + newLine +
                        'NAMESPACE=' + projectDevNamespace  + newLine +
                        'NAME=' + appName  + newLine +
                        'oc tag ${PIPELINES_NAMESPACE}/${NAME}:${BUILD_TAG} ${NAMESPACE}/${NAME}:${BUILD_TAG}' + newLine +
                        'oc project ${NAMESPACE}' + newLine +
                        'oc patch dc ${NAME} -p "spec:' + newLine +
                        '  template:' + newLine +
                        '    spec:' + newLine +
                        '      containers:' + newLine +
                        '        - name: ${NAME}' + newLine +
                        '          image: \'docker-registry.default.svc:5000/${NAMESPACE}/${NAME}:${BUILD_TAG}\'' + newLine +
                        '          env:' + newLine +
                        '            - name: NODE_ENV' + newLine +
                        '              value: \'test\'"' + newLine +
                        'oc rollout latest dc/${NAME}')
            }
            openShiftDeploymentVerifier {
                apiURL('')
                depCfg(appName)
                namespace(projectDevNamespace)
                // This optional field's value represents the number expected running pods for the deployment for the DeploymentConfig specified.
                replicaCount('1')
                authToken('')
                verbose('yes')
                // This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached.
                verifyReplicaCount('yes')
                waitTime('')
                waitUnit('sec')
            }
        }
        publishers {
            notifySlack(delegate)
        }
    }



    job(deployProd) {
        description(jobDescription)
        parameters {
            string{
                name("BUILD_TAG")
                defaultValue("my-app-build.1234")
                description("The BUILD_TAG is the \${JOB_NAME}.\${BUILD_NUMBER} of the successful build to be promoted.")
            }
        }
        rotateLogs(delegate)

        wrappers {
            buildWrappers(delegate)

        }
        steps {
            steps {
                shell('#!/bin/bash' + newLine +
                        'set -o xtrace' + newLine +
                        'PIPELINES_NAMESPACE=' + pipelineNamespace  + newLine +
                        'NAMESPACE=' + projectTestNamespace  + newLine +
                        'NAME=' + appName  + newLine +
                        'oc tag ${PIPELINES_NAMESPACE}/${NAME}:${BUILD_TAG} ${NAMESPACE}/${NAME}:${BUILD_TAG}' + newLine +
                        'oc project ${NAMESPACE}' + newLine +
                        'oc patch dc ${NAME} -p "spec:' + newLine +
                        '  template:' + newLine +
                        '    spec:' + newLine +
                        '      containers:' + newLine +
                        '        - name: ${NAME}' + newLine +
                        '          image: \'docker-registry.default.svc:5000/${NAMESPACE}/${NAME}:${BUILD_TAG}\'' + newLine +
                        '          env:' + newLine +
                        '            - name: NODE_ENV' + newLine +
                        '              value: \'production\'"' + newLine +
                        'oc rollout latest dc/${NAME}')
            }
            openShiftDeploymentVerifier {
                apiURL('')
                depCfg(appName)
                namespace(projectTestNamespace)
                // This optional field's value represents the number expected running pods for the deployment for the DeploymentConfig specified.
                replicaCount('1')
                authToken('')
                verbose('yes')
                // This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached.
                verifyReplicaCount('yes')
                waitTime('')
                waitUnit('sec')
            }
        }
        publishers {
            notifySlack(delegate)
        }
    }
}

buildMonitorView('microservice-monitor') {
    description('All build jobs for the vue app')
    filterBuildQueue()
    filterExecutors()
    jobs {
        regex(".*microservice.*")
    }
}
